regulator: Removed debug entries to fix the following compile error:
drivers/built-in.o:s2mps11.c:function s2mps11_pmic_probe: error: undefined reference to 'get_sec_debug_level'

Conflicts:
	drivers/regulator/s2mps11.c

Change-Id: I4cf6977ef62cc8df2b93d2fae81fc284c7e9d13a